### ISSUE TITLE
The same liability score for cases in WTCCC

### ISSUE THREAD

**Issue by borangao** [omerwe/LEAP#7]
Hi Omer,

Thanks for developing such good software. I am currently using WTCCC binary traits to create liability scores for downstream analysis. 
I first checked if LEAP runs well on my side by doing test.py. I found the liability scores generated in dataset1.phe.liab matches the 6th column in the fam file there. So I assume that my coding there is correct.
And I applied the LEAP there for RA and T1d in WTCCC data. I used the raw genotype data with about 300k SNPs. I have 2938 controls, and different numbers of cases for different traits.  I found the liability scores for cases are all the same and are different among controls, which is suspicious. I am wondering if you have any ideas about why it happens there.

Best,
Boran

**Comment by omerwe** [comment]
Hi Boran,

This makes sense - for rare phenotypes, the MAP estimate of case liabilities is almost always exactly equal to the liability threshold. This is consistent with the distribution of the liabilities in case-control datasets: A person is unlikely to be a case to begin with, so if they are a case, they probably were just "unlucky" enough to barely pass the liability threshold. In fact, it's exponentially less likely to have liability greater than the threshold (see Supplementary Figure 1 in the LEAP paper).

Hope it's clear, please let me know if not.

Cheers,

Omer
